/*
Gang Assign Time
Gang Closure Time
Ticket Resolution Time (S&D resolve time)
Ticket Status
Dispatcher Ticket Closure Time
TAT
Ticket SLA
Dispatcher Name
Dipatched Time
S&D Name */

export const data = {
  "tasks": [
    {
      "id": 199773,
      "ticket_number": "tkt-20250819040534-9482",
      "caller_name": "MR.SHIRAZUL ISLAM",
      "caller_contact": "01552305954",
      "complain_address": "House-G/10,Road-5,Area- BTCl koloni,]Ward-19,Thana -Bonani",
      "query_category": "Phase",
      "connection_category": "LT",
      "remarks": "Customer have complained that there is no electricity in some houses due to phase problem.",
      "exact_address": "House-G/10,Road-5,Area- BTCL Colony,]Ward-19,Thana -Banani",
      "query_id": null,
      "connection_status": null,
      "connection_account_status": null,
      "status": "RESOLVED",
      "is_emergency": null,
      "is_information_correct": 1,
      "is_exact_address": 0,
      "is_active_user": 1,
      "completion_time": null,
      "caller_id": 32006092,
      "dispatcher_id": 550,
      "snd_id": 7,
      "fieldforce_id": null,
      "assigned_by": null,
      "sanctioned_phase": "1",
      "latitude": 23.78631454429947,
      "longitude": 90.40694912439947,
      "created_at": "2025-08-19 04:03:11",
      "updated_at": "2025-08-19 08:31:13",
      "fieldforce_latitude": null,
      "fieldforce_longitude": null,
      "reopen": 0,
      "query_sub_category": "ফেজ সমস্যা (পাচ্ছে না/ কেটে গেছে/ উল্টো ঘুরে/ পরিবর্তন)",
      "nearby_points": "BTCL Boro Mosjid",
      "created_by": "Zakaria Ahmed",
      "landmarks": "House-G/10",
      "dispatcher_name": "Al Fahad Suvo",
      "snd_name": "Gulshan S&D Division",
      "fieldforce_name": null,
      "dispatched_time": 0.065555555555556,
      "resolved_time": "2025-08-19 08:31:13",
      "customer_phone": "01552315662",
      "assign_time": null,
      "dispatch_time": "2025-08-19 04:07:07",
      "pre_completion_time": null,
      "closed_time": null,
      "ticket_sla": null,
      "etd_total_time": null,
      "reopen_remarks": null
    },
    {
      "id": 199850,
      "ticket_number": "tkt-20250819032720-1317",
      "caller_name": "Md.Mojammel haqe",
      "caller_contact": "01711593191",
      "complain_address": "House-26, Road-12, Block-F, Area-Gulshan-1 Niketon, Thana-Gulshan",
      "query_category": "Short circuit",
      "connection_category": null,
      "remarks": "Customer complained of sparking on the power line.",
      "exact_address": "House-26, Road-12, Block-F, Area-Gulshan-1 Niketon, Thana-Gulshan",
      "query_id": null,
      "connection_status": null,
      "connection_account_status": null,
      "status": "RESOLVED",
      "is_emergency": null,
      "is_information_correct": 1,
      "is_exact_address": 1,
      "is_active_user": null,
      "completion_time": null,
      "caller_id": null,
      "dispatcher_id": 545,
      "snd_id": 7,
      "fieldforce_id": null,
      "assigned_by": null,
      "sanctioned_phase": null,
      "latitude": 23.771881779999987,
      "longitude": 90.40719822,
      "created_at": "2025-08-19 15:24:52",
      "updated_at": "2025-08-19 21:59:12",
      "fieldforce_latitude": null,
      "fieldforce_longitude": null,
      "reopen": 0,
      "query_sub_category": "বিদ্যুৎতের লাইনে স্পার্কিং হচ্ছে",
      "nearby_points": "Beside Of Brac Bank",
      "created_by": "Semi Khatun",
      "landmarks": "House-26",
      "dispatcher_name": "Hujaifa Chowdhury Ayatii",
      "snd_name": "Gulshan S&D Division",
      "fieldforce_name": null,
      "dispatched_time": 0.0725,
      "resolved_time": "2025-08-19 21:59:12",
      "customer_phone": null,
      "assign_time": null,
      "dispatch_time": "2025-08-19 15:29:13",
      "pre_completion_time": null,
      "closed_time": null,
      "ticket_sla": null,
      "etd_total_time": null,
      "reopen_remarks": null
    },
    {
      "id": 199908,
      "ticket_number": "tkt-20250819073446-7874",
      "caller_name": "MD.",
      "caller_contact": "01660182567",
      "complain_address": "Road-Hokers Merket, Area-Amtoli, Thana-Banani",
      "query_category": "Wire",
      "connection_category": null,
      "remarks": "Customer complained that the electrical wire caught fire.",
      "exact_address": "Road-Hokers Merket, Area-Amtoli, Thana-Banani",
      "query_id": null,
      "connection_status": null,
      "connection_account_status": null,
      "status": "RESOLVED",
      "is_emergency": null,
      "is_information_correct": 1,
      "is_exact_address": 0,
      "is_active_user": null,
      "completion_time": null,
      "caller_id": null,
      "dispatcher_id": 545,
      "snd_id": 7,
      "fieldforce_id": null,
      "assigned_by": null,
      "sanctioned_phase": null,
      "latitude": 23.78102,
      "longitude": 90.3985,
      "created_at": "2025-08-19 19:32:18",
      "updated_at": "2025-08-19 22:30:51",
      "fieldforce_latitude": null,
      "fieldforce_longitude": null,
      "reopen": 0,
      "query_sub_category": "তারে আগুন জ্বলছে",
      "nearby_points": "Pollice Box",
      "created_by": "Hujaifa Chowdhury Ayatii",
      "landmarks": null,
      "dispatcher_name": "Hujaifa Chowdhury Ayatii",
      "snd_name": "Gulshan S&D Division",
      "fieldforce_name": null,
      "dispatched_time": 0.0097222222222222,
      "resolved_time": "2025-08-19 22:30:51",
      "customer_phone": null,
      "assign_time": null,
      "dispatch_time": "2025-08-19 19:32:53",
      "pre_completion_time": null,
      "closed_time": null,
      "ticket_sla": null,
      "etd_total_time": null,
      "reopen_remarks": null
    },
    {
      "id": 199932,
      "ticket_number": "tkt-20250819095237-6093",
      "caller_name": "KAZI SHAMSUDDIN",
      "caller_contact": "01889996465",
      "complain_address": "House-PA/84, Alatun Nessa School Road, Area- Moddho Badda, Ward-97, Thana-Badda",
      "query_category": "Phase",
      "connection_category": "LT",
      "remarks": "Customer complained that there was no electricity in his residence due to phase problem.",
      "exact_address": "House-PA/84, Alatun Nessa School Road, Area- Moddho Badda, Ward-97, Thana-Badda.",
      "query_id": null,
      "connection_status": null,
      "connection_account_status": null,
      "status": "RESOLVED",
      "is_emergency": null,
      "is_information_correct": 1,
      "is_exact_address": 0,
      "is_active_user": 10,
      "completion_time": null,
      "caller_id": 33043911,
      "dispatcher_id": 545,
      "snd_id": 7,
      "fieldforce_id": null,
      "assigned_by": null,
      "sanctioned_phase": "1",
      "latitude": 23.77676151956077,
      "longitude": 90.4237545239132,
      "created_at": "2025-08-19 21:50:15",
      "updated_at": "2025-08-19 22:32:14",
      "fieldforce_latitude": null,
      "fieldforce_longitude": null,
      "reopen": 0,
      "query_sub_category": "ফেজ সমস্যা (পাচ্ছে না/ কেটে গেছে/ উল্টো ঘুরে/ পরিবর্তন)",
      "nearby_points": "Alatun Nessa School Behind",
      "created_by": "Al Hasan Akash",
      "landmarks": "House-PA/84,",
      "dispatcher_name": "Hujaifa Chowdhury Ayatii",
      "snd_name": "Gulshan S&D Division",
      "fieldforce_name": null,
      "dispatched_time": 0.013055555555556,
      "resolved_time": "2025-08-19 22:32:14",
      "customer_phone": "01823433356",
      "assign_time": null,
      "dispatch_time": "2025-08-19 21:51:02",
      "pre_completion_time": null,
      "closed_time": null,
      "ticket_sla": null,
      "etd_total_time": null,
      "reopen_remarks": null
    },
    {
      "id": 199950,
      "ticket_number": "tkt-20250820125240-7254",
      "caller_name": "Fountain view Resturent",
      "caller_contact": "01320391358",
      "complain_address": "Fountain View Restaurant, Road-police plaza, Area- Gulshan-1,Thana Gulshan Model,",
      "query_category": "Meter",
      "connection_category": "LT",
      "remarks": "Customer has complained that there is no electricity in his home even though there is sufficient balance in his meter. DQM",
      "exact_address": "Fountain View Restaurant, Road-police plaza, Area- Gulshan-1,Thana Gulshan Model,",
      "query_id": null,
      "connection_status": null,
      "connection_account_status": null,
      "status": "RESOLVED",
      "is_emergency": null,
      "is_information_correct": 1,
      "is_exact_address": 0,
      "is_active_user": 10,
      "completion_time": null,
      "caller_id": 41317217,
      "dispatcher_id": 550,
      "snd_id": 7,
      "fieldforce_id": null,
      "assigned_by": null,
      "sanctioned_phase": "1",
      "latitude": 23.7728539,
      "longitude": 90.4162317,
      "created_at": "2025-08-20 00:50:17",
      "updated_at": "2025-08-20 09:00:04",
      "fieldforce_latitude": null,
      "fieldforce_longitude": null,
      "reopen": 0,
      "query_sub_category": "মিটারে টাকা আছে কিন্তু বিদ্যুৎ চলে গেছে",
      "nearby_points": "police plaza",
      "created_by": "Shuvongkar Palwan",
      "landmarks": "Fountain View Restaurant",
      "dispatcher_name": "Al Fahad Suvo",
      "snd_name": "Gulshan S&D Division",
      "fieldforce_name": null,
      "dispatched_time": 0.29361111111111,
      "resolved_time": "2025-08-20 09:00:04",
      "customer_phone": "01680726825",
      "assign_time": null,
      "dispatch_time": "2025-08-20 01:07:54",
      "pre_completion_time": null,
      "closed_time": null,
      "ticket_sla": null,
      "etd_total_time": null,
      "reopen_remarks": null
    },
    {
      "id": 199986,
      "ticket_number": "tkt-20250820101408-1990",
      "caller_name": "Anisur Rahman",
      "caller_contact": "00258811064",
      "complain_address": "House-99, Area-Mohakhalii, Sowkot alo sorok, Thana-Gulshan.",
      "query_category": "Phase",
      "connection_category": null,
      "remarks": "Alternative Number - 01978096622\nCustomer have complained that there is no electricity in some houses due to phase problem.",
      "exact_address": "House-99, Area- Mohakhalii, Sowkot ali sorok, Thana-Gulshan.",
      "query_id": null,
      "connection_status": null,
      "connection_account_status": null,
      "status": "RESOLVED",
      "is_emergency": null,
      "is_information_correct": 1,
      "is_exact_address": 0,
      "is_active_user": null,
      "completion_time": null,
      "caller_id": null,
      "dispatcher_id": 544,
      "snd_id": 7,
      "fieldforce_id": null,
      "assigned_by": null,
      "sanctioned_phase": null,
      "latitude": 23.773036766469314,
      "longitude": 90.40644524707034,
      "created_at": "2025-08-20 10:11:41",
      "updated_at": "2025-08-20 14:43:44",
      "fieldforce_latitude": null,
      "fieldforce_longitude": null,
      "reopen": 0,
      "query_sub_category": "ফেজ সমস্যা (পাচ্ছে না/ কেটে গেছে/ উল্টো ঘুরে/ পরিবর্তন)",
      "nearby_points": "Bon Vaban",
      "created_by": "Hujaifa Chowdhury Ayatii",
      "landmarks": "House-99",
      "dispatcher_name": "Utsab Ghosh",
      "snd_name": "Gulshan S&D Division",
      "fieldforce_name": null,
      "dispatched_time": 0.023888888888889,
      "resolved_time": "2025-08-20 14:43:44",
      "customer_phone": null,
      "assign_time": null,
      "dispatch_time": "2025-08-20 10:13:07",
      "pre_completion_time": null,
      "closed_time": null,
      "ticket_sla": null,
      "etd_total_time": null,
      "reopen_remarks": null
    },
    {
      "id": 200002,
      "ticket_number": "tkt-20250820121354-1181",
      "caller_name": "PARAMOUNT INSURANCE COMPANY LTD.",
      "caller_contact": "01343965454",
      "complain_address": "House-23,Road-35,area-Gulshan central moshjid er pashe,Thana-Gulshan",
      "query_category": "Shut down",
      "connection_category": "LT",
      "remarks": "Customer complained that there is no electricity in his home.",
      "exact_address": "House-23,Road-35,area-Gulshan central moshjid ,Thana-Gulshan",
      "query_id": null,
      "connection_status": null,
      "connection_account_status": null,
      "status": "RESOLVED",
      "is_emergency": null,
      "is_information_correct": 1,
      "is_exact_address": 0,
      "is_active_user": 1,
      "completion_time": null,
      "caller_id": 18009715,
      "dispatcher_id": 544,
      "snd_id": 7,
      "fieldforce_id": null,
      "assigned_by": null,
      "sanctioned_phase": "3",
      "latitude": 23.78987235376882,
      "longitude": 90.41349237464146,
      "created_at": "2025-08-20 12:11:32",
      "updated_at": "2025-08-20 14:41:24",
      "fieldforce_latitude": null,
      "fieldforce_longitude": null,
      "reopen": 0,
      "query_sub_category": "নিজ নিবাসে বিদ্যুৎ নেই",
      "nearby_points": "Gulshan azad moshjid",
      "created_by": "Tazmun Nahar Tonni",
      "landmarks": "House-23",
      "dispatcher_name": "Utsab Ghosh",
      "snd_name": "Gulshan S&D Division",
      "fieldforce_name": null,
      "dispatched_time": 0.047777777777778,
      "resolved_time": "2025-08-20 14:41:24",
      "customer_phone": "01777705429",
      "assign_time": null,
      "dispatch_time": "2025-08-20 12:14:24",
      "pre_completion_time": null,
      "closed_time": null,
      "ticket_sla": null,
      "etd_total_time": null,
      "reopen_remarks": null
    },
    {
      "id": 200007,
      "ticket_number": "tkt-20250820122903-7452",
      "caller_name": "MRS. KHISHOWER SHOFI CHOWDHURY",
      "caller_contact": "01682711644",
      "complain_address": "HOUSE-1/B, ROAD-71, Area- Gulshan  2,Thana- Gulshan.",
      "query_category": "Shut down",
      "connection_category": "LT",
      "remarks": "Customer complained that there is no electricity in his home.",
      "exact_address": "House-1/B, Road-71, Area- Gulshan 2, Thana- Gulshan.",
      "query_id": null,
      "connection_status": null,
      "connection_account_status": null,
      "status": "RESOLVED",
      "is_emergency": null,
      "is_information_correct": 1,
      "is_exact_address": 0,
      "is_active_user": 1,
      "completion_time": null,
      "caller_id": 32019234,
      "dispatcher_id": 544,
      "snd_id": 7,
      "fieldforce_id": null,
      "assigned_by": null,
      "sanctioned_phase": "1",
      "latitude": 23.80413314336647,
      "longitude": 90.413669116812,
      "created_at": "2025-08-20 12:26:45",
      "updated_at": "2025-08-20 14:46:00",
      "fieldforce_latitude": null,
      "fieldforce_longitude": null,
      "reopen": 0,
      "query_sub_category": "নিজ নিবাসে বিদ্যুৎ নেই",
      "nearby_points": "United hospital",
      "created_by": "Panna Kawser Monne",
      "landmarks": "HOUSE-1/B",
      "dispatcher_name": "Utsab Ghosh",
      "snd_name": "Gulshan S&D Division",
      "fieldforce_name": null,
      "dispatched_time": 0.062222222222222,
      "resolved_time": "2025-08-20 14:46:00",
      "customer_phone": "01713065451",
      "assign_time": null,
      "dispatch_time": "2025-08-20 12:30:29",
      "pre_completion_time": null,
      "closed_time": null,
      "ticket_sla": null,
      "etd_total_time": null,
      "reopen_remarks": null
    },
    {
      "id": 200145,
      "ticket_number": "tkt-20250821095514-9690",
      "caller_name": "ABDUL KAIUM",
      "caller_contact": "01788681620",
      "complain_address": "House-K/112/14,Area- Somitir Math, Dokhin Badda, Ward- 21, Thana-Badda",
      "query_category": "Meter",
      "connection_category": "LT",
      "remarks": "Customer has complained that there is no electricity in his home even though there is sufficient balance in his meter.",
      "exact_address": "House-K/112/14, Area- Somitir Math, Dokhin Badda, Ward- 21, Thana-Badda",
      "query_id": null,
      "connection_status": null,
      "connection_account_status": null,
      "status": "RESOLVED",
      "is_emergency": null,
      "is_information_correct": 1,
      "is_exact_address": 0,
      "is_active_user": 10,
      "completion_time": null,
      "caller_id": 33041203,
      "dispatcher_id": 545,
      "snd_id": 7,
      "fieldforce_id": null,
      "assigned_by": null,
      "sanctioned_phase": "1",
      "latitude": 23.773173223814528,
      "longitude": 90.42266216129066,
      "created_at": "2025-08-21 09:52:52",
      "updated_at": "2025-08-21 10:59:12",
      "fieldforce_latitude": null,
      "fieldforce_longitude": null,
      "reopen": 0,
      "query_sub_category": "মিটারে টাকা আছে কিন্তু বিদ্যুৎ চলে গেছে",
      "nearby_points": "Brac university 3 Number gate",
      "created_by": "Teresa Sarkar",
      "landmarks": null,
      "dispatcher_name": "Hujaifa Chowdhury Ayatii",
      "snd_name": "Gulshan S&D Division",
      "fieldforce_name": null,
      "dispatched_time": 0.25944444444444,
      "resolved_time": "2025-08-21 10:59:12",
      "customer_phone": "01672164493",
      "assign_time": null,
      "dispatch_time": "2025-08-21 10:08:26",
      "pre_completion_time": null,
      "closed_time": null,
      "ticket_sla": null,
      "etd_total_time": null,
      "reopen_remarks": null
    },
    {
      "id": 200152,
      "ticket_number": "tkt-20250821102749-7216",
      "caller_name": "Khaleda Begum",
      "caller_contact": "01531743521",
      "complain_address": "House-kh98, Road- Nani Barir Mor, Area-  Dokhin Badda, Ward- 21, Thana- Badda",
      "query_category": "Meter",
      "connection_category": "LT",
      "remarks": "Customer has complained that there is no electricity in his home even though there is sufficient balance in his meter.",
      "exact_address": "House-KH-98, Road-Nani Barir Mor, Area-Dokhin Badda, Ward- 21, Thana-Badda",
      "query_id": null,
      "connection_status": null,
      "connection_account_status": null,
      "status": "RESOLVED",
      "is_emergency": null,
      "is_information_correct": 1,
      "is_exact_address": 0,
      "is_active_user": 10,
      "completion_time": null,
      "caller_id": 41295049,
      "dispatcher_id": 545,
      "snd_id": 7,
      "fieldforce_id": null,
      "assigned_by": null,
      "sanctioned_phase": "1",
      "latitude": 23.77426859,
      "longitude": 90.42359423,
      "created_at": "2025-08-21 10:25:26",
      "updated_at": "2025-08-21 11:05:28",
      "fieldforce_latitude": null,
      "fieldforce_longitude": null,
      "reopen": 0,
      "query_sub_category": "মিটারে টাকা আছে কিন্তু বিদ্যুৎ চলে গেছে",
      "nearby_points": "Dokhin Badda Jame Mosjid",
      "created_by": "Mst Karima Akter",
      "landmarks": "House-kh98",
      "dispatcher_name": "Hujaifa Chowdhury Ayatii",
      "snd_name": "Gulshan S&D Division",
      "fieldforce_name": null,
      "dispatched_time": 0.17416666666667,
      "resolved_time": "2025-08-21 11:05:28",
      "customer_phone": "01641056415",
      "assign_time": null,
      "dispatch_time": "2025-08-21 10:35:53",
      "pre_completion_time": null,
      "closed_time": null,
      "ticket_sla": null,
      "etd_total_time": null,
      "reopen_remarks": null
    },
    {
      "id": 200162,
      "ticket_number": "tkt-20250821115628-4873",
      "caller_name": "Md Sabbir",
      "caller_contact": "01799036423",
      "complain_address": "House-3, Road-2, Area- Gulshan-1, Block-SWH, Thana-Gulshan",
      "query_category": "Phase",
      "connection_category": null,
      "remarks": "Customer have complained that there is no electricity in some houses due to phase problem.",
      "exact_address": "House-3, Road-2, Area- Gulshan-1, Block-SWH, Thana-Gulshan.",
      "query_id": null,
      "connection_status": null,
      "connection_account_status": null,
      "status": "RESOLVED",
      "is_emergency": null,
      "is_information_correct": 1,
      "is_exact_address": 0,
      "is_active_user": null,
      "completion_time": null,
      "caller_id": null,
      "dispatcher_id": 545,
      "snd_id": 7,
      "fieldforce_id": null,
      "assigned_by": null,
      "sanctioned_phase": null,
      "latitude": 23.77496496281798,
      "longitude": 90.41528856906825,
      "created_at": "2025-08-21 11:54:00",
      "updated_at": "2025-08-21 12:08:41",
      "fieldforce_latitude": null,
      "fieldforce_longitude": null,
      "reopen": 0,
      "query_sub_category": "ফেজ সমস্যা (পাচ্ছে না/ কেটে গেছে/ উল্টো ঘুরে/ পরিবর্তন)",
      "nearby_points": "Police Plaza",
      "created_by": "Nuraia Jannti meem",
      "landmarks": "House-3,",
      "dispatcher_name": "Hujaifa Chowdhury Ayatii",
      "snd_name": "Gulshan S&D Division",
      "fieldforce_name": null,
      "dispatched_time": 0.16583333333333,
      "resolved_time": "2025-08-21 12:08:41",
      "customer_phone": null,
      "assign_time": null,
      "dispatch_time": "2025-08-21 12:03:57",
      "pre_completion_time": null,
      "closed_time": null,
      "ticket_sla": null,
      "etd_total_time": null,
      "reopen_remarks": null
    },
    {
      "id": 200258,
      "ticket_number": "tkt-20250821111554-8046",
      "caller_name": "REHANA BEGUM",
      "caller_contact": "01521424599",
      "complain_address": "House-190/2, Road- Bou Bazer Road, Area- Baluchor Middile Badda,Thana-Badda",
      "query_category": "Meter",
      "connection_category": "LT",
      "remarks": "Customer has complained that there is no electricity in his home even though there is sufficient balance in his meter.",
      "exact_address": "House-190/2, Road- Bou Bazer Road, Area- Baluchor Middile Badda,Thana-Badda",
      "query_id": null,
      "connection_status": null,
      "connection_account_status": null,
      "status": "RESOLVED",
      "is_emergency": null,
      "is_information_correct": 1,
      "is_exact_address": 0,
      "is_active_user": 10,
      "completion_time": null,
      "caller_id": 19039817,
      "dispatcher_id": 550,
      "snd_id": 7,
      "fieldforce_id": null,
      "assigned_by": null,
      "sanctioned_phase": "1",
      "latitude": 23.77852280705577,
      "longitude": 90.42201840470352,
      "created_at": "2025-08-21 23:13:33",
      "updated_at": "2025-08-22 08:37:50",
      "fieldforce_latitude": null,
      "fieldforce_longitude": null,
      "reopen": 0,
      "query_sub_category": "মিটারে টাকা আছে কিন্তু বিদ্যুৎ চলে গেছে",
      "nearby_points": "Badda High School",
      "created_by": "Emon KumarGhosh",
      "landmarks": "House-190/2",
      "dispatcher_name": "Al Fahad Suvo",
      "snd_name": "Gulshan S&D Division",
      "fieldforce_name": null,
      "dispatched_time": 0.086944444444444,
      "resolved_time": "2025-08-22 08:37:50",
      "customer_phone": "01793527955",
      "assign_time": null,
      "dispatch_time": "2025-08-21 23:18:46",
      "pre_completion_time": null,
      "closed_time": null,
      "ticket_sla": null,
      "etd_total_time": null,
      "reopen_remarks": null
    },
    {
      "id": 200259,
      "ticket_number": "tkt-20250821114615-8834",
      "caller_name": "REHANA BEGUM",
      "caller_contact": "01784880892",
      "complain_address": "house-Ta/190/2, Road- boubazar road, Balurchar,",
      "query_category": "Meter",
      "connection_category": "LT",
      "remarks": "Customer has complained that there is no electricity in his home even though there is sufficient balance in his meter.",
      "exact_address": "House-Ta/190/2, Road- Boubazar Road, Area-Balurchar, Thana- Badda.",
      "query_id": null,
      "connection_status": null,
      "connection_account_status": null,
      "status": "RESOLVED",
      "is_emergency": null,
      "is_information_correct": 1,
      "is_exact_address": 0,
      "is_active_user": 10,
      "completion_time": null,
      "caller_id": 19039817,
      "dispatcher_id": 550,
      "snd_id": 7,
      "fieldforce_id": null,
      "assigned_by": null,
      "sanctioned_phase": "1",
      "latitude": 23.77852280705577,
      "longitude": 90.42201840470352,
      "created_at": "2025-08-21 23:43:53",
      "updated_at": "2025-08-21 23:52:29",
      "fieldforce_latitude": null,
      "fieldforce_longitude": null,
      "reopen": 0,
      "query_sub_category": "মিটারে টাকা আছে কিন্তু বিদ্যুৎ চলে গেছে",
      "nearby_points": "Badda high school",
      "created_by": "Ferdaus Rahman",
      "landmarks": "house-Ta/190/2",
      "dispatcher_name": "Al Fahad Suvo",
      "snd_name": "Gulshan S&D Division",
      "fieldforce_name": null,
      "dispatched_time": 0.029722222222222,
      "resolved_time": "2025-08-21 23:52:29",
      "customer_phone": "01793527955",
      "assign_time": null,
      "dispatch_time": "2025-08-21 23:45:40",
      "pre_completion_time": null,
      "closed_time": null,
      "ticket_sla": null,
      "etd_total_time": null,
      "reopen_remarks": null
    },
    {
      "id": 200312,
      "ticket_number": "tkt-20250822112523-1389",
      "caller_name": "MR ALHAJ AMDUL HALIM",
      "caller_contact": "01834809859",
      "complain_address": "House-Cha-144/3, Area-Mohakhali TV Gate, Ward-20, Thana-Banani",
      "query_category": "Shut down",
      "connection_category": "LT",
      "remarks": "Customer complained that there is no electricity in his home.",
      "exact_address": "House-Cha-144/3, Area -Mohakhali TV Gate, Ward-20, Thana-Banani",
      "query_id": null,
      "connection_status": null,
      "connection_account_status": null,
      "status": "RESOLVED",
      "is_emergency": null,
      "is_information_correct": 1,
      "is_exact_address": 0,
      "is_active_user": 1,
      "completion_time": null,
      "caller_id": 32035282,
      "dispatcher_id": 544,
      "snd_id": 7,
      "fieldforce_id": null,
      "assigned_by": null,
      "sanctioned_phase": "1",
      "latitude": 23.77927066,
      "longitude": 90.40744666,
      "created_at": "2025-08-22 11:23:01",
      "updated_at": "2025-08-22 12:01:09",
      "fieldforce_latitude": null,
      "fieldforce_longitude": null,
      "reopen": 0,
      "query_sub_category": "নিজ নিবাসে বিদ্যুৎ নেই",
      "nearby_points": "Behinde of BRAC Universty",
      "created_by": "Ripon Das",
      "landmarks": "House-Cha-144/3",
      "dispatcher_name": "Utsab Ghosh",
      "snd_name": "Gulshan S&D Division",
      "fieldforce_name": null,
      "dispatched_time": 0.0225,
      "resolved_time": "2025-08-22 12:01:09",
      "customer_phone": "01687833221",
      "assign_time": null,
      "dispatch_time": "2025-08-22 11:24:22",
      "pre_completion_time": null,
      "closed_time": null,
      "ticket_sla": null,
      "etd_total_time": null,
      "reopen_remarks": null
    },
    {
      "id": 200334,
      "ticket_number": "tkt-20250822030753-3527",
      "caller_name": "MR ENTHAKHABUL HAMID",
      "caller_contact": "01725048951",
      "complain_address": "House-15, Road-122, Area-Gulshan-1, Thana-Gulshan",
      "query_category": "Phase",
      "connection_category": "LT",
      "remarks": "Customer complained that one of the three phases is not working.",
      "exact_address": "House-15, Road-122, Area-Gulshan-1, Thana-Gulshan",
      "query_id": null,
      "connection_status": null,
      "connection_account_status": null,
      "status": "RESOLVED",
      "is_emergency": null,
      "is_information_correct": 1,
      "is_exact_address": 0,
      "is_active_user": 1,
      "completion_time": null,
      "caller_id": 32022198,
      "dispatcher_id": 544,
      "snd_id": 7,
      "fieldforce_id": null,
      "assigned_by": null,
      "sanctioned_phase": "1",
      "latitude": 23.785680940369122,
      "longitude": 90.4190957066808,
      "created_at": "2025-08-22 15:05:31",
      "updated_at": "2025-08-22 15:27:31",
      "fieldforce_latitude": null,
      "fieldforce_longitude": null,
      "reopen": 0,
      "query_sub_category": "ফেজ সমস্যা (পাচ্ছে না/ কেটে গেছে/ উল্টো ঘুরে/ পরিবর্তন)",
      "nearby_points": "122 No Road",
      "created_by": "Semi Khatun",
      "landmarks": "House-15,",
      "dispatcher_name": "Utsab Ghosh",
      "snd_name": "Gulshan S&D Division",
      "fieldforce_name": null,
      "dispatched_time": 0.0175,
      "resolved_time": "2025-08-22 15:27:31",
      "customer_phone": "01788174488",
      "assign_time": null,
      "dispatch_time": "2025-08-22 15:06:34",
      "pre_completion_time": null,
      "closed_time": null,
      "ticket_sla": null,
      "etd_total_time": null,
      "reopen_remarks": null
    },
    {
      "id": 200344,
      "ticket_number": "tkt-20250822034759-9396",
      "caller_name": "Managing Director- ACE Development Ltd.",
      "caller_contact": "01713240018",
      "complain_address": "House-11, Road-4, Block-F, Area- Bonani Chiarmen Bari, Ward-19, Thana-Bonani",
      "query_category": "Phase",
      "connection_category": "LT",
      "remarks": "Customer have complained that there is no electricity in some houses due to phase problem.",
      "exact_address": "House-11, Road-4, Block-F, Area- Banani Chiarmen Bari, Ward-19, Thana-Banani",
      "query_id": null,
      "connection_status": null,
      "connection_account_status": null,
      "status": "RESOLVED",
      "is_emergency": null,
      "is_information_correct": 1,
      "is_exact_address": 0,
      "is_active_user": 1,
      "completion_time": null,
      "caller_id": 41305918,
      "dispatcher_id": 547,
      "snd_id": 7,
      "fieldforce_id": null,
      "assigned_by": null,
      "sanctioned_phase": "3",
      "latitude": 23.78885895039812,
      "longitude": 90.40068075431184,
      "created_at": "2025-08-22 15:45:37",
      "updated_at": "2025-08-22 17:37:16",
      "fieldforce_latitude": null,
      "fieldforce_longitude": null,
      "reopen": 0,
      "query_sub_category": "ফেজ সমস্যা (পাচ্ছে না/ কেটে গেছে/ উল্টো ঘুরে/ পরিবর্তন)",
      "nearby_points": "Bonani Chiarmen Bari Mosjid",
      "created_by": "Emon KumarGhosh",
      "landmarks": "House-11,",
      "dispatcher_name": "Md. Rohan Mahmud",
      "snd_name": "Gulshan S&D Division",
      "fieldforce_name": null,
      "dispatched_time": 0.014444444444444,
      "resolved_time": "2025-08-22 17:37:16",
      "customer_phone": "01711567403",
      "assign_time": null,
      "dispatch_time": "2025-08-22 15:46:29",
      "pre_completion_time": null,
      "closed_time": null,
      "ticket_sla": null,
      "etd_total_time": null,
      "reopen_remarks": null
    },
    {
      "id": 200419,
      "ticket_number": "tkt-20250823081722-8545",
      "caller_name": "DR. MOAZZAM HOSSAIN",
      "caller_contact": "01989479059",
      "complain_address": "House- 77/B,Road-3,Block-F, Area-BANANI, Thana-Banani",
      "query_category": "Phase",
      "connection_category": "LT",
      "remarks": "Customer complained that there was no electricity in his residence due to phase problem.",
      "exact_address": "House- 77/B,Road-3,Block-F, Area-BANANI, Thana-Banani",
      "query_id": null,
      "connection_status": null,
      "connection_account_status": null,
      "status": "RESOLVED",
      "is_emergency": null,
      "is_information_correct": 1,
      "is_exact_address": 0,
      "is_active_user": 1,
      "completion_time": null,
      "caller_id": 32008798,
      "dispatcher_id": 544,
      "snd_id": 7,
      "fieldforce_id": null,
      "assigned_by": null,
      "sanctioned_phase": "3",
      "latitude": 23.78844456,
      "longitude": 90.40299188,
      "created_at": "2025-08-23 08:15:01",
      "updated_at": "2025-08-23 08:24:05",
      "fieldforce_latitude": null,
      "fieldforce_longitude": null,
      "reopen": 0,
      "query_sub_category": "ফেজ সমস্যা (পাচ্ছে না/ কেটে গেছে/ উল্টো ঘুরে/ পরিবর্তন)",
      "nearby_points": "Beside Of Banani Model School",
      "created_by": "Semi Khatun",
      "landmarks": "House- 77/B,",
      "dispatcher_name": "Utsab Ghosh",
      "snd_name": "Gulshan S&D Division",
      "fieldforce_name": null,
      "dispatched_time": 0.021111111111111,
      "resolved_time": "2025-08-23 08:24:05",
      "customer_phone": "01989479059",
      "assign_time": null,
      "dispatch_time": "2025-08-23 08:16:17",
      "pre_completion_time": null,
      "closed_time": null,
      "ticket_sla": null,
      "etd_total_time": null,
      "reopen_remarks": null
    },
    {
      "id": 200469,
      "ticket_number": "tkt-20250823122742-1135",
      "caller_name": "MD. IQBAL HOSSEN BHUIYAN",
      "caller_contact": "01742966648",
      "complain_address": "Holding -B-48, Road- Puraton kacha bazar road, Arera- Mohakhali bazar , Thana- Bonani",
      "query_category": "Phase",
      "connection_category": "LT",
      "remarks": "Customer have complained that there is no electricity in some houses due to phase problem.",
      "exact_address": "Holding -B-48, Road- Puraton kacha bazar road, Arera- Mohakhali bazar , Thana- Bonani",
      "query_id": null,
      "connection_status": null,
      "connection_account_status": null,
      "status": "RESOLVED",
      "is_emergency": null,
      "is_information_correct": 1,
      "is_exact_address": 0,
      "is_active_user": 1,
      "completion_time": null,
      "caller_id": 32037855,
      "dispatcher_id": 544,
      "snd_id": 7,
      "fieldforce_id": null,
      "assigned_by": null,
      "sanctioned_phase": "1",
      "latitude": 23.778981139999978,
      "longitude": 90.39934189000009,
      "created_at": "2025-08-23 12:25:20",
      "updated_at": "2025-08-23 12:40:11",
      "fieldforce_latitude": null,
      "fieldforce_longitude": null,
      "reopen": 0,
      "query_sub_category": "ফেজ সমস্যা (পাচ্ছে না/ কেটে গেছে/ উল্টো ঘুরে/ পরিবর্তন)",
      "nearby_points": "New Dhaka Holtel",
      "created_by": "Ripon Das",
      "landmarks": "Holding -B-48",
      "dispatcher_name": "Utsab Ghosh",
      "snd_name": "Gulshan S&D Division",
      "fieldforce_name": null,
      "dispatched_time": 0.0069444444444444,
      "resolved_time": "2025-08-23 12:40:11",
      "customer_phone": "01742966648",
      "assign_time": null,
      "dispatch_time": "2025-08-23 12:25:45",
      "pre_completion_time": null,
      "closed_time": null,
      "ticket_sla": null,
      "etd_total_time": null,
      "reopen_remarks": null
    },
    {
      "id": 200579,
      "ticket_number": "tkt-20250824125511-2909",
      "caller_name": "MD. NIJAM UDDIN",
      "caller_contact": "01712118769",
      "complain_address": "House- TA-160/3/B, Area-Modho Badda, High School Road, Thana Badda",
      "query_category": "Short circuit",
      "connection_category": "LT",
      "remarks": "Customer complained of sparking on the power line.",
      "exact_address": "House- TA-160/3/B, Area-Modho Badda, High School Road, Thana Badda",
      "query_id": null,
      "connection_status": null,
      "connection_account_status": null,
      "status": "RESOLVED",
      "is_emergency": null,
      "is_information_correct": 1,
      "is_exact_address": 0,
      "is_active_user": 10,
      "completion_time": null,
      "caller_id": 41141729,
      "dispatcher_id": 547,
      "snd_id": 7,
      "fieldforce_id": null,
      "assigned_by": null,
      "sanctioned_phase": "1",
      "latitude": 23.779576394410892,
      "longitude": 90.42183464322785,
      "created_at": "2025-08-24 00:52:50",
      "updated_at": "2025-08-24 10:08:53",
      "fieldforce_latitude": null,
      "fieldforce_longitude": null,
      "reopen": 0,
      "query_sub_category": "বিদ্যুৎতের লাইনে স্পার্কিং হচ্ছে",
      "nearby_points": "Badda High School Road",
      "created_by": "Shuvongkar Palwan",
      "landmarks": "House- TA-160/3/B",
      "dispatcher_name": "Md. Rohan Mahmud",
      "snd_name": "Gulshan S&D Division",
      "fieldforce_name": null,
      "dispatched_time": 0.015277777777778,
      "resolved_time": "2025-08-24 10:08:53",
      "customer_phone": "01680682019",
      "assign_time": null,
      "dispatch_time": "2025-08-24 00:53:45",
      "pre_completion_time": null,
      "closed_time": null,
      "ticket_sla": null,
      "etd_total_time": null,
      "reopen_remarks": null
    }
  ],
  "status": 200,
  "count": 19
}